language: ruby

services:
  - postgresql

addons:
  postgresql: "9.4"

rvm:
  - 2.5.1

before_script:
  - psql -c 'create database "cita_dapps_test";' -U postgres
  - cp .env.test.local.travis .env.test.local

branches:
  only:
    - master
    - develop
    - release

env:
  global:
    - RAILS_ENV=test

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
  - bundle install
  - nvm install 8.11.2
  - node -v
  - npm i -g yarn
  - yarn

script:
  - bundle exec rails db:migrate
  - bundle exec rails test

after_success:
  - bash <(curl -s https://codecov.io/bash)
