version: '3'
services:
  db:
    image: postgres:10.5
    volumes:
    - ./docker/data:/var/lib/postgresql/data
  app:
    image: cyton_dapps_app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    # volumes:
    #   - .:/app # for local debug
    command: bundle exec puma -C config/puma.docker.rb
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 8080:80
