# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 156d5350814b22f87d9355a6b60ae7c7b35a7763a8921f9d90289bbba4182734249f4037e2ed9ccb18a2b5764d8d3bc47809b77face1e10bf9b910ed6fb7557c

test:
  secret_key_base: b640a53c351ff56f2d79fdabb798aadef73b3dec7ddf051b78a215051de5b3a3f9e3ebb78dee3a71177d6d4cad988ca0863ca42ec63b235555618fc1ecc1802b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
